website/base/urls.py
from django.urls import path, include
from . import views


app_name = "base"

urlpatterns = [
    
    path('', views.home_view, name='home'),
    path('staff', views.staff_view, name='staff'),
    path('gateways/', views.gateway_view, name='gateways'),
    path('gateway/<gateway_id>/', views.edit_gateway_view, name='edit_gateway'),
    path('settings/', views.settings_view, name='settings'),
    path('accounts/signin/', views.ClientSigninView.as_view(), name='signin'),
    path('accounts/signup/', views.ClientSignupView.as_view(), name='signup'),
    path('home/admin/', views.admin_view, name='super_admin'),
    path('home/admin/edit/<admin_id>/', views.edit_admin_view, name='edit-user'),
    path('home/access/', views.access_view, name='access'),
    path('home/admin/create-role/', views.create_role_view, name='create-role'),
    path('home/admin/create-role-subadmin/', views.create_role_subadmin, name='create-role-subadmin'),
    path('home/admin/create-user/', views.create_user_view, name='create-user'),
    path('home/admin/member/', views.add_member_view, name='member'),
    path('support/', views.support_view, name='support'),
    path('home/support/<int:id>/', views.support_detail_view, name='support'),
    path('home/support/', views.admin_support_view, name='admin_support'),
    path('home/support/chat/<str:args>', views.support_chat, name='support_ticket'),
    path('home/report/', views.admin_report_view, name='report'),
    path('home/number/', views.ani_view, name='ani'),
    path('home/number/<ani_id>/<admin_id>/', views.edit_ani_view, name='edit_ani'),

    # shortened Url
    path('<str:short_url>', views.visit_real_url, name='visit_real_url'),
    path('shortened-url/', views.shortened_url, name='shortened_url')

]

website/website/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('way_to_superadmin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('', include('base.urls')),
    path('campaigns/', include('responder.urls')),
    path('telnyx/', include('telnyx_sms.urls')),
    path('signalwire/', include('SignalWire.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns


admin.site.site_header = "SMS Responder"
admin.site.site_title = "Square Reach"

website/base/models.py
from django.db import models
from django.contrib.auth import get_user_model
from responder.models import (
    Admin

)


User = get_user_model()


class ShortenedUrl(models.Model):
    admin = models.ForeignKey(Admin, on_delete=models.CASCADE)
    hash_code = models.CharField(max_length=15, null=True)
    given_url = models.CharField(max_length=250)
    shortened_url = models.CharField(max_length=250)

    def __str__(self):
        return self.given_url


class Messenger(models.Model):
    name = models.CharField(max_length=15)

    def __str__(self):
        return self.name
        
class Support(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    messenger = models.ForeignKey(Messenger, on_delete=models.CASCADE)
    msgr_id = models.CharField(max_length=20)
    subject = models.CharField(max_length=100)
    message = models.TextField()
    is_close = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message

class DefaultNotification(models.Model):
    user_default = models.TextField(null=True,blank=True)
    visitor_default = models.TextField(null=True,blank=True)

    def __str__(self):
        return self.user_default

class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    notification = models.TextField(null=True,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

class Contact(models.Model):
    email = models.EmailField(blank=True, null=True)
    phone = models.CharField(max_length=15,blank=True, null=True)
    skype = models.CharField(max_length=25,blank=True, null=True)
    telegram = models.CharField(max_length=25,blank=True, null=True)

    def __str__(self):
        return self.email

class Chat(models.Model):
    admin = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    sent = models.TextField(blank=True, null=True)
    received = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_created = models.BooleanField(default=False)

    def __str__(self):
        return self.admin.username

class CronTest(models.Model):
    test = models.CharField(max_length=50)

    def __str__(self):
        return self.test

website/base/views.py
import os, re, random, json, datetime
from datetime import timedelta, date

import re
from datetime import timedelta, datetime, date
import csv
import string

from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from allauth.account.views import SignupView, LoginView
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect

from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.core.validators import validate_email
from django.contrib.auth import authenticate, login
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Q
from django.contrib.auth.models import User as U
from django.utils.translation import gettext_lazy as _


from django.contrib.sites.models import Site
from responder.models import (
        Gateway,
        AddGateway,
        AssignContact,
        Admin,
        Ani,
        AssignedAni,
        CronJob,
        InOutSms,
        UserPassword,
        PrimaryNumber,
    )
from .models import (
        Messenger,
        Support,
        Chat,
        ShortenedUrl
    )

User = get_user_model()


def visit_real_url(request, short_url):
    if request.method == "GET":
        real_urls = ShortenedUrl.objects.filter(hash_code=short_url.strip())
        if real_urls:
            return HttpResponseRedirect(real_urls[0].given_url)
    return HttpResponse(status=400)


def hash_generator(size=9, chars=string.ascii_uppercase + string.digits):
    return ''.join(random.choice(chars) for _ in range(size))

def shortened_url(request):

    if request.method == 'GET':
        urls = ShortenedUrl.objects.filter(admin__admin=request.user)
        if urls:
            urls = list(urls.values())
        else:
            urls = ''

        data = {
            'urls': urls
        }
        return JsonResponse(data=data, status=200)

    if request.is_ajax():
        data = json.loads(request.body)
        check = data['check']
        if check =="shorten_url":
            given_url = data.get("given_url")

            while True:
                hash_code = hash_generator()
                print(hash_code)
                if not ShortenedUrl.objects.filter(hash_code=hash_code).exists():
                    domain = Site.objects.all()[0].domain
                    shortened_url = domain + '/' + hash_code
                    break
                else:
                    continue

            if hash_code:
                admin_obj = get_object_or_404(Admin, admin=request.user)

                ShortenedUrl.objects.create(
                    admin = admin_obj,
                    hash_code = hash_code,
                    given_url = given_url,
                    shortened_url = shortened_url
                )

            return JsonResponse(data=data, status=200)

        elif check == "get_url":
            url_id = data.get("url_id")

            url = list(ShortenedUrl.objects.filter(id=url_id).values())[0]

            data = {
                'url': url
            }

            return JsonResponse(data=data, status=200)

        elif check == "update_url":
            url = data.get('url')
            url_id = url.get("id")
            given_url = url.get("given_url")
            
            ShortenedUrl.objects.filter(id=url_id).update(given_url=given_url)
            
            data = {

            }

            return JsonResponse(data=data, status=200)

        elif check == "delete_url":
            url_id = data.get("url_id")
            ShortenedUrl.objects.filter(id=url_id).delete()

            data = {

            }

            return JsonResponse(data=data, status=200)

def edit_ani_view(request, ani_id, admin_id):
    
    assigned_anis = ''

    if request.method == "POST":
        name = request.POST.get('name')
        ani = request.POST.get('phone')
        gateway_id = request.POST.get("gateway_id")
        admin_ids = request.POST.getlist('admin_id')
        print(admin_ids)

        Ani.objects.filter(id=ani_id).update(

                name = name,
                gateway_id = gateway_id,
                ani = ani
            )
        if admin_ids:
            objs = AssignedAni.objects.filter(ani_id=ani_id)
            if objs:
                print("ysssssss")
                objs.delete()
            for admin_id in admin_ids:
                AssignedAni.objects.create(
                        ani_id = ani_id,
                        admin_id = admin_id
                    
                    )
        return redirect('base:ani')

    ani = Ani.objects.filter(id=ani_id)[0]
    users = Admin.objects.all()
    if users:
        admin_ids = AssignedAni.objects.filter(ani_id=ani_id)
        assigned_admins = []
        for item in admin_ids:
            assigned_admins.append(item.admin_id)
            print(assigned_admins)
            users = users.exclude(admin_id__in=assigned_admins)
            print(users)

    gateways = AddGateway.objects.all()
    assigned_anis = AssignedAni.objects.filter(ani_id=ani_id)
    
    context = {
        'ani':ani,
        'assigned_anis':assigned_anis,
        # 'assigned_contact':assigned_contact,
        'users': users,
        'gateways': gateways
    }
    return render(request, 'base/edit_ani.html', context)

def ani_view(request):
    if request.user.is_superuser:
        gateways = AddGateway.objects.all()
        if request.is_ajax():
            data = json.loads(request.body)
            check = data.get("check")
            if check == "remove_ani":
                ani_ids = data.get("ani_ids")
                Ani.objects.filter(id__in=ani_ids).delete()

        elif request.method == "POST" and not request.is_ajax():
            name = request.POST.get("name")
            ani = request.POST.get("phone")
            gateway_id = request.POST.get("gateway_id")
            admin = get_object_or_404(Admin, admin=request.user)
            Ani.objects.create(
                    name = name,
                    gateway_id = gateway_id,
                    admin = admin,
                    ani = ani
                )
            return redirect(reverse("base:ani"))

        context = {
            'gateways': gateways
        }
        return render(request, 'base/ani.html', context)

def clear_media():
    """
    Cleared all media files while formatting db
    """
    from pathlib import Path
    import glob, os


    BASE_DIR = Path(__file__).resolve().parent.parent

    path = os.path.join(BASE_DIR, "media/gallery/")
    files = glob.glob("{}*".format(path))
    for path in files:
        os.remove(path)

@login_required
def support_chat(request, args):
    admin = ""
    user = ""
    if request.method == "POST":
        check = request.POST.get("check")
        if check == "send" or check == "received":
            received = request.POST.get("received")
            sent = request.POST.get("sent")
            admin_obj = get_object_or_404(User, username = args)
            Chat.objects.create(admin=admin_obj, sent=sent, received=received)
        elif check == "create":
            user = request.POST.get("user")
            Chat.objects.filter(admin__username=user).update(is_created=True)

    if request.user.is_superuser or request.user.is_staff:
        admin = args
    else:
        admin = request.user
    chats = Chat.objects.filter(admin__username = admin)
    if chats:
        user = chats[0].admin

    context = {
        "chats":chats,
        "user": user,
    }

    if request.is_ajax() and request.method=='POST':
        pass

    return render(request, 'base/chats.html', context)

def support_view(request):
    alert = ""
    messangers = ""
    ticket_created = False
    try:
        messangers = Messenger.objects.all()
    except:
        pass
    try:
        ticket_created = Chat.objects.filter(admin=request.user,is_created=True).exists()
    except:
        pass
    if request.method == "POST":
        check = request.POST['check']
        if check == "support":
            msg_id = request.POST['messanger']
            messanger_id = request.POST['messanger_id']
            subject = request.POST['subject']
            message = request.POST['message']
            msg_obj = get_object_or_404(Messenger, id=msg_id)
            try:
                Support.objects.create(user=request.user, messenger=msg_obj, subject=subject,message=message,msgr_id=messanger_id)
                admin_obj = get_object_or_404(User, username=request.user)
                Chat.objects.create(admin = admin_obj, received=message)
                alert = "Ticket created Succesfully"
            except:
                error = 'Something went wrong'
                pass

    context = {
        "alert":alert,
        "messangers":messangers,
        "ticket_created":ticket_created
    }
    return render(request, 'base/support.html', context)

@login_required
def admin_support_view(request):
    support = ""
    alert = ""
    error = ""
    if request.method =="POST":
        check = request.POST['check']
        if check == 'delete':
            support_id = request.POST['support_id']
            try:
                user_id = Support.objects.filter(id=support_id)[0].user_id
                Chat.objects.filter(admin_id=user_id).delete()
                Support.objects.filter(id=support_id).delete()
                alert = "Deleted Succesfully"
            except:
                error = "Something went wrong"
        elif check == "chat":
            admin = request.POST['admin']

            return redirect("base:support_ticket", admin)
        elif check == 'close':
            support_id = request.POST['support_id']
            try:

website/templates/base/ad-partial.html
{% if request.user.is_superuser %}
	<!-- confirmation modal before clearing db -->
	<div id="confirm-modal" class="modal fade bg-dark" role="dialog">
        <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
          <div class="modal-header">
            <h4 class="modal-title sweet-text text-center letter-spacing">Confirmation </h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>
          <div class="modal-body">
            <div class="form-group">
               <label for="usr">Confirmation Text:</label>
               <input autocomplete="off" placeholder="Type 'Confirm'" type="text" class="form-control" id="delete">
            </div>            
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button @click.prevent="deleteAllSms()" type="button" class="btn btn-danger" data-dismiss="modal">Confirm</button>
          </div>
        </div>
      </div>
    </div>
	<div class="row">
		<ul class="nav flex-column">
			<li class="nav-item">
				<a class="nav-link ml-lg-1 btn-hover color-8 letter-spacing" href="{% url 'base:super_admin' %}">User Panel</a>
			</li>
			{% comment %} <li class="nav-item">
				<a class="nav-link ml-lg-1 btn-hover color-11 letter-spacing" href="{% url 'base:create-role' %}">Permission</a>
			</li> {% endcomment %}
			{% if request.user.is_superuser %}					
				<li class="nav-item">
					<a 
						class="nav-link ml-lg-1 btn-hover color-11 letter-spacing" 
						href="{% url 'base:ani' %}">Numbers</a>
				</li>
			{% endif %}
		</ul>
	</div>
{% endif %}

website/templates/base/chats.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Chats {% endblock %}

{% block content %}

<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-xl-4 offset-xl-1 card shadow p-3">
                    <h3 class="pl-2 letter-spacing title-gradient animate__animated animate__slideInRight">
                        <i class="fas fa-sms mr-3 ml-2 text-primary"></i><span class="">Chat Room</span></h3>
                </div>
                <div class="col-xl-7">
                    <ol class="breadcrumb float-sm-right h6">
                        <li class="breadcrumb-item"><a href="{% url 'base:home' %}">Home</a></li>
                        <li class="breadcrumb-item text-warning">Chat Room</li>
                    </ol>
                </div>
            </div>
            <div class="row">
                <div class="col-xl-8 offset-xl-2" style="overflow-y: scroll;font-size:14px; font-weight: 500; height: 600px;">
                    {% for item in chats %}
                        {% if item.sent %}
                            <div class="p-0 px-3 py-2 bg-default ml-5 card rounded border">
                                <p class="p-0 m-0">{{ item.sent }}</p>
                                <div class="p-0 m-0">
                                    <p class="float-right m-0 p-0 text-secondary" style="font-size: 10px;">{{ item.timestamp }}</p>
                                </div>
                            </div>
                        {% endif %}
                        {% if item.received %}
                            <div class="p-0 px-3 py-2 bg-dark mr-5 card rounded">
                                <p class="p-0 m-0 text-white">{{ item.received }}</p>
                                <div class="p-0 m-0">
                                    <p class="float-right m-0 p-0 text-white" style="font-size: 10px;">{{ item.timestamp }}</p>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
            <form method="POST" class="">
            {% csrf_token %}
                <div class="row pt-4">
                    <div class="col-xl-5 offset-xl-3">
                        {% if request.user.is_superuser or request.user.is_staff %}
                            <div class="form-group">
                                <textarea name="sent" placeholder="Type anything" class="form-control rounded-pill" rows="2"></textarea>
                            </div>
                        {% else %}
                            <div class="form-group">
                                <textarea name="received" placeholder="Type anything" class="form-control rounded-pill" rows="2"></textarea>
                            </div>
                        {% endif %}
                    </div>
                    {% if request.user.is_superuser or request.user.is_staff %}
                        <div class="col-xl-3">
                            <input type="hidden" name="user" value="{{ user }}">
                            <button name="check" value="send" type="submit" class="text-spacing btn btn-primary ml-3 px-4 py-2 mb-2">Reply</button>
                            <button name="check" value="create" class="btn btn-warning ml-3 px-4 py-2 mb-2">create</button>
                        </div>
                    {% else %}
                        <div class="col-xl-3">
                            <input type="hidden" name="user" value="{{ user }}">
                            <button name="check" value="received" type="submit" class="text-spacing btn btn-primary ml-3 px-4 py-2 mb-2">Send</button>
                        </div>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
    <section class="content" id="app">
        <div class="container-fluid">
            <div class="row">
                <div class="col-xl-10 offset-xl-1 animate__animated animate__fadeInUp">
                </div>
            </div>
        </div>
    </section>
</div>

{% endblock %}
{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
<script type="text/javascript" src="{% static 'vue/conversation.js' %}"></script>
{% endblock %}

website/templates/base/create-user.html
{% extends 'base.html' %}
{% block title %} Create User {% endblock %}

{% block content %}
{% if request.user.is_superuser %}
    <div class="content-wrapper">
        <section class="content">
            <div class="container-fluid">
                {% include 'base/ad-partial.html' %}
            </div>
            <div class="row px-lg-4 py-4">
                <div class="col-lg-6">
                    <div class="card shadow p-5">
                        <div class="card-body">
                            <form method="post">
                            {% csrf_token %}
                                <div class="input-group">
                                    <span class="input-group-addon pr-3"><i class="far fa-user fa-2x"></i></span>
                                    <input id="email" type="text" class="form-control" name="user" placeholder="Enter Username">
                                </div>
                                <div class="input-group pt-3">
                                    <span class="input-group-addon pr-3"><i class="fas fa-unlock-alt fa-2x"></i></span>
                                    <input id="password" type="password" class="form-control" name="password" placeholder="Password">
                                </div>
                                <button class="btn btn-primary mt-3 float-right" name="check" value="create-user">Submit</button>
                            </form>    
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>

{% endif %}
{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script>
        {% if alert %}
            const Toast = Swal.mixin({
                    toast: true,
                    position: 'top-end',
                    showConfirmButton: false,
                    timer: 1500,
                    timerProgressBar: true,
                    didOpen: (toast) => {
                        toast.addEventListener('mouseenter', Swal.stopTimer)
                        toast.addEventListener('mouseleave', Swal.resumeTimer)
                    }
                })

                Toast.fire({
                    icon: 'success',
                    title: '{{ alert }}!!'

                })
        {% elif error %}
            const Toast = Swal.mixin({
                    toast: true,
                    position: 'top-end',
                    showConfirmButton: false,
                    timer: 1500,
                    timerProgressBar: true,
                    didOpen: (toast) => {
                        toast.addEventListener('mouseenter', Swal.stopTimer)
                        toast.addEventListener('mouseleave', Swal.resumeTimer)
                    }
                })

                Toast.fire({
                    icon: 'error',
                    title: 'OOps! {{ error }} ??'

                })
        {% endif %}

    </script>
{% endblock %}
{% endblock %}

website/templates/base/edit_gateway.html
{% extends 'base.html' %}
{% block content %}
	<section class="content-wrapper py-1 py-lg-5">
		<div class="row">
			<div class="col-md-5 mx-auto">
				<div class="card">
					<div class="card-header">
						<p class="h4 bold-2 sweet-text text-oswald">Edit Gateway</p>
					</div>
					<div class="card-body px-lg-5 px-1 py-1 py-lg-4">
						<form method="post">
							{% csrf_token %}
							<div class="form-group">
								<label>Name *</label>
								<input type="text" name="name" class="form-control" value="{{gateway.name}}">
							</div>
							<div class="form-group">
								<label>API Key *</label>
								<input type="text" name="api_key" class="form-control" value="{{gateway.tel_api}}">
							</div>
							<div class="form-group">
								<label>CONNECTION TOKEN *</label>
								<input type="text" name="connection_id" class="form-control" value="{{gateway.tel_connection_id}}">
							</div>
							<div class="float-right">
								<button type="submit" class="btn btn-primary">Update</button>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

website/templates/base/support.html
{% extends 'base.html' %}
{% block title %}Support{% endblock %}
{% block content %}
<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 offset-lg-3 py-5">
                    <div class="card shadow-1 border-0 mt-3 px-4 py-4">
                        <div class="card-body">
                            {% if alert %}
                                <div class="mb-5 text-center border py-4">
                                    <p class="h6 text-secondary">Your ticket is successfully created. We sincerely take care your issue with our system. Someone from support team will contact to you within 24 hours.</p>
                                    <a class="" href="{% url 'base:home' %}">Back to Dashboard</a>
                                </div>
                            {% endif %}                            
                            {% if ticket_created %}
                                <div class="mb-5 text-center border py-4">
                                    <p class="h6 text-secondary">Please click on the link below to speak to support</p>
                                    <a class="text-primary font-weight-bold" href="/home/support/chat/{{ request.user }}">Click Here</a>
                                </div>
                            {% endif %}
                            {% if not request.user.is_authenticated %}
                                <p class="h5 text-center">Hi <span class="text-primary h4"></span>, tell us if you are stuck in anywhere</p>
                                <p class="text-center">Please Fill out the form below to reach us.</p>
                            {% else %}
                                <p class="h5 text-center">Hi <span class="text-primary h4">{{ request.user }}</span>, tell us if you are stuck in anywhere</p>
                                <p class="text-center">Please Fill out the form below to reach us.</p>
                            {% endif %}
                            <div class="pt-5">
                                <form class="form-horizontal" method="POST">
                                {% csrf_token %}
                                    <div class="form-group">
                                        <label class="" for="gateways">Select Messanger*</label>
                                        <select class="form-control" id="gateways" name="messanger" required>
                                            <option class="bg-secondary" value="" selected disabled>Select Messanger</option>
                                            {% if messangers %}
                                                {% for item in messangers %}
                                                    <option value=" {{ item.id }}" required>{{ item.name }}</option>
                                                {% endfor %}
                                            {% endif %}
                                        </select>
                                    </div> 
                                    <div class="form-group">
                                        <label for="pwd">Messanger ID*</label>
                                        <input type="text" name="messanger_id" class="form-control" id="pwd" required>
                                    </div>
                                    <div class="form-group">
                                        <label for="pwd">Subject*</label>
                                        <input type="text" placeholder="Why you are reaching us? " name="subject" class="form-control" id="pwd" required>
                                    </div>
                                    <div class="form-group">
                                        <label class="" for="comment">Message*</label>
                                        <div class="">
                                            <textarea placeholder="Tell us your problem...." class="form-control pt-3 pl-3" rows="5" id="comment" name="message" required></textarea>                                    
                                        </div>
                                    </div>
                                    <button name="check" value="support" type="submit" class="mt-1 btn float-right btn-dark">Submit</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>
{% endblock %}
{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script>
        {% if alert %}
            const Toast = Swal.mixin({
                    toast: true,
                    position: 'top-end',
                    showConfirmButton: false,
                    timer: 1500,
                    timerProgressBar: true,
                    didOpen: (toast) => {
                        toast.addEventListener('mouseenter', Swal.stopTimer)
                        toast.addEventListener('mouseleave', Swal.resumeTimer)
                    }
                })

                Toast.fire({
                    icon: 'success',
                    title: '{{ alert }}!!'

                })
        {% elif error %}
            const Toast = Swal.mixin({
                    toast: true,
                    position: 'top-end',
                    showConfirmButton: false,
                    timer: 1500,
                    timerProgressBar: true,
                    didOpen: (toast) => {
                        toast.addEventListener('mouseenter', Swal.stopTimer)
                        toast.addEventListener('mouseleave', Swal.resumeTimer)
                    }
                })

                Toast.fire({
                    icon: 'error',
                    title: 'OOps! {{ error }} ??'

                })
        {% endif %}

    </script>
{% endblock %}