website/base/urls.py
from django.urls import path, include
from . import views


app_name = "base"

urlpatterns = [
    
    path('', views.home_view, name='home'),
    path('staff', views.staff_view, name='staff'),
    path('gateways/', views.gateway_view, name='gateways'),
    path('gateway/<gateway_id>/', views.edit_gateway_view, name='edit_gateway'),
    path('settings/', views.settings_view, name='settings'),
    path('accounts/signin/', views.ClientSigninView.as_view(), name='signin'),
    path('accounts/signup/', views.ClientSignupView.as_view(), name='signup'),
    path('home/admin/', views.admin_view, name='super_admin'),
    path('home/admin/edit/<admin_id>/', views.edit_admin_view, name='edit-user'),
    path('home/access/', views.access_view, name='access'),
    path('home/admin/create-role/', views.create_role_view, name='create-role'),
    path('home/admin/create-role-subadmin/', views.create_role_subadmin, name='create-role-subadmin'),
    path('home/admin/create-user/', views.create_user_view, name='create-user'),
    path('home/admin/member/', views.add_member_view, name='member'),
    path('support/', views.support_view, name='support'),
    path('home/support/<int:id>/', views.support_detail_view, name='support'),
    path('home/support/', views.admin_support_view, name='admin_support'),
    path('home/support/chat/<str:args>', views.support_chat, name='support_ticket'),
    path('home/report/', views.admin_report_view, name='report'),
    path('home/number/', views.ani_view, name='ani'),
    path('home/number/<ani_id>/<admin_id>/', views.edit_ani_view, name='edit_ani'),

    # shortened Url
    path('<str:short_url>', views.visit_real_url, name='visit_real_url'),
    path('shortened-url/', views.shortened_url, name='shortened_url')

]

website/responder/urls.py
from django.urls import path
from . import views


app_name = "responder"

urlpatterns = [
    path('undelivered', views.undel_messages_view, name='undelivered-messages'),
    path('gallery/<int:cam_id>/', views.gallery_view, name='gallery'),
    path('cronjob/', views.cronjob_view, name='cronjob'),
    path('cron/bulk', views.cronjob_bulk_view, name='cronjob_bulk'),
    path('response/edit/<int:cam_id>/<int:resp_id>/', views.response_edit_view, name='response-edit'),
    path('leads/<int:id>', views.lead_view, name='leads'),
    path('leads/conversations/<str:dnis>', views.chat_details, name='conversations'),
    path('conversations/', views.side_conversations_view, name='side-conversations'),
    path('pineapple/incoming', views.pineapple_response, name='pineapple-response'),
    path('pineapple/dlr', views.pineapple_dlr, name='pineapple-dlr'),
    path('undelivered/<int:cam_id>/', views.undelivered_view, name='undelivered'),
    path('delivered/<int:cam_id>/', views.delivered_view, name='delivered'),
    path('registration/', views.registration_view, name='registration'),
    path('test/<slug:slug>', views.test_view, name='test'),
    path('autoresponders/', views.auto_responders_view, name='auto-responders'),
    path('autoresponders/<int:resp_id>/', views.auto_responders_edit_view, name='auto-responders'),
    path('keywords/', views.keywords_view, name='keywords'),
    path('keywords/<int:keyword_id>/', views.edit_keyword_view, name='edit_keyword'),
    path('bulk-sms/', views.import_view, name='bulk-sms'),
    path('primary-number/', views.pn_view, name='primary_number'),
]

website/website/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('way_to_superadmin/', admin.site.urls),
    path('admin/', include('admin_honeypot.urls', namespace='admin_honeypot')),
    path('', include('base.urls')),
    path('campaigns/', include('responder.urls')),
    path('telnyx/', include('telnyx_sms.urls')),
    path('signalwire/', include('SignalWire.urls')),
    path('accounts/', include('allauth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns


admin.site.site_header = "SMS Responder"
admin.site.site_title = "Square Reach"

website/templates/partials/aside.html
{% load static %}
{% load head_tags %}

<div id="aside">
    <div id="notification" class="modal fade" role="dialog">
      <div class="modal-dialog modal-lg">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title sweet-text font-weight-bold letter-spacing text-uppercase">Notifications</h5>
            </div>
            <div class="modal-body">
            {% if request.user.is_authenticated %}
                {% if default %}
                    <div class="alert alert-light">
                        <p>{{ default.user_default }}</p>
                    </div>
                {% endif %}
                {% if messages %}
                    {% for item in messages %}
                        <div class="alert alert-light">
                            <p>{{ item.notification }}</p>
                            <p class="float-right font-weight-bold" style="font-size:11px">{{ item.timestamp }}</p>
                        </div>
                    {% endfor %}
                {% endif %}
                {% if not default and not messages %}
                    <div class="alert alert-light">
                        <p>No notification to show</p>                
                    </div>
                {% endif %}
            {% else %}
                {% if default %}
                    <div class="alert alert-light">
                        <p>{{ default.visitor_default }}</p>
                    </div>
                {% endif %}
            {% endif %}
          </div>
          <div class="modal-footer">
            <button id="close-modal" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>   
    <!-- facebook modal -->
    <aside class="aside hidden" id="aside">
        <!-- Sidebar -->
        <div class="sidebar hidden text-oswald m-0 p-0">
            <div class="side-img pt-5">
                <div class="user-panel d-flex align-items-center">
                	{% if request.user.is_authenticated %}
        	            <div class="image text-white">
        	                <img src="{% static 'assets/dist/img/profile.png' %}" class="text-white" alt="User Image">
        	            </div>
        	        {% endif %}
                    {% if request.user.is_authenticated %}
        	            <div class="h5 text-spacing">
        	                <a href="{% url 'base:home' %}" class="font-quicksand text-white pl-2">{{ request.user.username }}</a>
        	            </div>
        	        {% endif %}
                </div>
                {% if not request.user.is_superuser %}
                    <div class="pt-3 text-white">
                        <p class="pl-4 mb-0" @click='pn()'>Primary Number</p>
                            {% for item in user_anis %}
                                <p class="pl-4 mt-0" @click='pn()' v-model='primary_number'>. {{ item.ani.ani|phone_number }}</p>
                            {% endfor %}
                    </div>
                {% endif %}
            </div>
            <!-- Sidebar Menu -->
            <nav class="mt-2" id="sm-menu">
                <ul class="nav nav-pills nav-sidebar sm-font flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    {% comment %} <li class="nav-item animate__animated">
                        <a href="{% url 'base:home' %}" class="nav-link translatex">
                            <i class="nav-icon text-white fas fa-tachometer-alt"></i>
                            <p>
                                Dashboard
                            </p>
                        </a>
                    </li> {% endcomment %}
                    {% if request.user.is_authenticated %}
                        <li class="nav-item d-flex" id="campaigns">
                            <a href="{% url 'responder:side-conversations' %}" class="nav-link translatex">
                                <i class="nav-icon fad text-white fa-comments-alt"></i>
                                <p>
                                    Inbox
                                </p>
                                <span class="text-white ml-2 my-1 p-1 rounded-pill bg-white">{{unread_count}}</span>
                            </a>
                        </li>
                    {% endif %}
                    {% if request.user.is_superuser %}
                        <li class="nav-item has-treeview">
                            <a href="{% url 'base:super_admin' %}" class="nav-link translatex" style="cursor: pointer;">
                                <i class="nav-icon text-white fas fa-chart-line"></i>
                                <p>
                                    Access Control
                                </p>
                            </a>
                        </li>
    	            {% endif %}
                    {% if request.user.is_superuser %}
                        <li class="nav-item">
                            <a href="{% url 'base:gateways' %}" class="nav-link translatex">
                                <i class="fad fa-dungeon nav-icon text-white"></i>
                                <p>
                                    SMS Gateways
                                </p>
                            </a>
                        </li>
                    {% endif %}             

                    <li class="nav-item mt-5 text-center">
                    	{% if not request.user.is_authenticated %}
                        	<a href="{% url 'base:signin' %}" class="btn btn-outline-info mr-2 translatex">Login</a>
                        	<a href="{% url 'base:signup' %}" class="btn btn-outline-info translatex">Signup</a>
                        {% endif %}
                    </li>
                </ul>
            </nav>
            <!-- sidebar-menu -->
        </div>
        <!-- sidebar -->
    </aside>
    <!-- Main Sidebar Container -->
    <div class="header-main d-flex justify-content-between">
        <div class="row">
            <a class="nav-link active m-3 rounded" id="hamburger" data-widget="pushmenu" style="cursor:pointer;" role="button">
                <i class="fas fa-align-justify fa-1x" id="hamburger"></i>
            </a>
            <a href="{% url 'base:home' %}" class="sm-none text-uppercase h3 pl-xl-4 text-success pt-3">
                <p class='h2 bold-3'>Fax <span class='pl-2 text-primary'>Smart</p>
            </a>
        </div>
        <div class="pt-1 text-white">
            {% if request.user.is_superuser %}
               <div class="dropdown">
                    <p 
                        class="bold-1 pb-0 mb-1 text-oswald text-center"
                        style="letter-spacing:1px;">
                            {% if pn %}
                               {{pn.ani.name}}
                            {% endif %}
                    </p>
                    <button 
                        style="background-color:transparent; min-width: 230px; letter-spacing:1px" 
                        class="bold-1 border-0 btn btn-primary btn-sm dropdown-toggle text-center text-primary"
                        type="button" 
                        data-toggle="dropdown">
                            {% if pn %}
                               {{pn.ani.ani|phone_number}}
                            {% else %}
                                Set Primary Number
                            {% endif %}
                        <span class="caret"></span></button>
                            <ul 
                                class="dropdown-menu hidden p-0 m-0 w-100" 
                                style="height: 200px; min-width: 22rem; overflow-y:scroll!important ;">
                                {% for item in anis %}
                                    <li 
                                        @click="pn({{item.id}})"
                                        style="letter-spacing:1px" 
                                        class="pl-1 p-2 hover-white pointer border-bottom">
                                        {{item.ani|phone_number}} - {{item.name}}
                                        <span class="bg-secondary rounded-pill p-1 bold-1">{{item.not_responded}}</span>
                                    </li>
                                {% endfor %}
                            </ul>
                </div>
            {% endif %}
        </div>
        {% if request.user.is_authenticated %}
            <div class="mr-lg-2 mr-2 pt-2">
                <button v-if='!is_dropDown' @click='activateDropdown()' class="btn btn-warning px-3 py-0 m-0">
                    <i class="fas fa-angle-down"></i>
                </button>
                <button v-if='is_dropDown' @click='deactivateDropdown()' class="btn btn-warning px-3 py-0 m-0">
                    <i class="fas fa-angle-up"></i>
                </button>
            </div>
        {% endif %}
    </div>
    {% if request.user.is_authenticated %}
        <div v-if='is_dropDown' class="sidemenu-dropdown">
            <ul 
                class="hidden p-0 m-0 w-100 text-white text-center" 
                style="height: 200px; min-width: 15rem;;">
                {% if request.user.is_superuser %}
                    <li class="pl-2 p-2 hover-white pointer text-secondary bold-1 border-bottom">
                        <a 
                            target="_blank" 
                            class="text-primary" 
                            href="/way_to_superadmin/">Admin
                        </a>
                    </li>
                {% endif %}   
                <li class="pl-2 p-2 hover-white pointer text-secondary bold-1 border-bottom">
                    {% if request.user.is_authenticated and not request.session.user == "superuser" %}
                        <a href="{% url 'account_logout' %}" class="text-primary ml-1 mr-2">Logout</a>
                    {% elif request.session.user == "superuser" %}
                        <form method="post" action="{% url 'base:super_admin' %}">
                            {% csrf_token %}
                            <input type="hidden" name="user" value="{{ request.session.username }}">
                            <button type="submit" name="check" value="back_to_admin" class="btn btn btn-danger btn-sm ml-1 mr-2">Back</button>
                            
                        </form>
                    {% endif %}
                </li>
                <li class="pl-2 p-2 hover-white pointer text-secondary bold-1 border-bottom">
                        <span class="badge badge-warning text-white pointer px-2 py-1 ml-2">
                            {% now "SHORT_DATETIME_FORMAT" %}
                        </span>
                    </a>
                </li>
            </ul>
        </div> 
    {% endif %}
</div>
<script src="{% static 'vue/aside.js' %}"></script>

<script>
    sm_menu = document.querySelector(".aside");
    hamburger = document.querySelector("#hamburger");
    window.addEventListener("click", (e)=>{
        if (document.querySelector(".aside").contains(e.target)){

        }else{
            if (e.target.id ==="hamburger"){
                navshow();
            }
            else if (document.querySelector(".aside").classList.contains("open")){
                // console.log('yes')
                sm_menu.classList.toggle("open");

            }
        }
    });
    document.getElementById('notification-message').addEventListener("click", function(){
        if (document.getElementById("aside").classList.contains("open")){
            document.getElementById("aside").classList.toggle("open");
        }
    });
    document.getElementById("close-modal").addEventListener("click", function(){
        console.log("dsfsdf")
        document.getElementById("aside").classList.add("open");
       if (document.getElementById("aside").classList.contains("open")){
            document.getElementById("aside").classList.toggle("open");
        }else{
            document.getElementById("aside").classList.add("open");
        } 
    });
    function navshow(){
        // sm_menu.classList.remove("aside");
        sm_menu.classList.toggle("open");

    };

    access_control = document.querySelector(".has-treeview")
    access_control.addEventListener("click",()=>{
        right = document.querySelector(".right");
        if (right.classList.contains("fa-angle-left")){
            right.classList.remove("fa-angle-left");
            right.classList.add("fa-angle-down");
            tree_view = document.querySelector(".nav-treeview");
            tree_view.style.display="block";
        }else{
            right.classList.remove("fa-angle-down");
            right.classList.add("fa-angle-left");
            tree_view = document.querySelector(".nav-treeview");
            tree_view.style.display="none";
        }

    });

</script>
<script type="text/javascript">
    var current = location.href;
    var menu = document.getElementsByClassName("nav-link");
    for (let i = 0; i<menu.length; i++){
        if(menu[i].href === current){
            menu[i].classList.add("active-aside");
            break;
        }
    }
</script>
<script type="text/javascript">
    $('select').selectpicker();
</script>

website/templates/partials/head.html
{% load static %}

    <meta charset="utf-8">
    <meta http-equiv="Content-Security-Policy" content="upgrade-insecure-requests">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- IonIcons -->
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'assets/dist/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/responsive.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous"> -->

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">

    <script src="https://cdn.jsdelivr.net/npm/vue@2.6.12"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.21.1/axios.min.js"></script>
    <script src="https://unpkg.com/moment@2.26.0/moment.js"></script>
    <script type="text/javascript" src="{% static 'vue/main.js' %}"></script>

website/templates/partials/js.html
{% load static %}

<!-- Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>

<script src="{% static 'assets/plugins/chart.js/Chart.min.js' %}"></script>
<!-- AdminLTE -->
<script src="{% static 'assets/dist/js/adminlte.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>

<!-- bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js"></script>

<!-- bootstrap select -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>